import {calendarYear} from './world.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusLabels={alive:'在世',active:'在世',deceased:'已故',dead:'已故',moved:'迁居',away:'异地',detained:'暂受行动限制',missing:'失去联系'};
const status=value=>statusLabels[value]||value||'近况待知';
export const socialPlans={balanced:['兼顾各处','把时间分给熟人、工作与社区。'],family:['照应身边人','更多维系已有的往来。'],work:['工作与学业','在学习与谋生中增加接触。'],community:['走进社区','参与邻里活动，结识更多人。'],guarded:['保留私人空间','减少来往，留出自己的时间。']};
export function renderPopulation(data,filters,view,detail=null,loading=false){
  const p=data||view.population;
  const heading=`<div class="section-heading"><div><span class="eyebrow">Lives crossing yours</span><h1>人间来往</h1></div><p class="muted">他们有自己的日子，也有你尚不知道的一面。<br>这里留下你实际接触的人，以及传到你耳边的消息。</p></div>`;
  if(detail)return heading+renderPerson(detail,p,view,loading);
  return heading+`<section class="people-summary" aria-label="实际交往概况">${[['已知人物',p.known_count],['直接交往',p.direct_count],['曾经密切',p.close_ever_count??p.close_count],['持续关注',`${p.tracked_count} / ${p.focus_limit}`]].map(([label,count])=>`<div><strong>${esc(count??0)}</strong><span>${label}</span></div>`).join('')}</section><p class="small muted population-note">这一生的人群容量 ${esc(p.capacity)} 人，跨越不同世代；只有实际相遇或听闻的人会出现在这里。其中当前在世的密切关系 ${esc(p.close_count)} 人；曾经密切包括故人与后来疏远的人。</p>
  ${view.finished?'':`<details class="social-plan-panel"><summary>日常交往安排 · ${esc(socialPlans[p.plan]?.[0]||p.plan)} <span class="small">随年份推进</span></summary><div class="social-plans">${Object.entries(socialPlans).map(([id,[label,description]])=>`<button class="social-plan ${id===p.plan?'selected':''}" data-social-plan="${id}" ${id===p.plan?'disabled':''}><strong>${label}</strong><span>${description}</span></button>`).join('')}</div><p class="small muted">安排会影响今后的实际接触，不会立即增加亲近。每年最多调整三次。</p></details>`}
  <form id="people-filter-form" class="people-filters"><label><span>查找已知人物</span><input name="query" maxlength="80" value="${esc(filters.query)}" placeholder="姓名、职业或身份"></label><label><span>关系范围</span><select name="group">${Object.entries({known:'所有已知人物',direct:'直接交往过',close:'密切关系',important:'持续关注',deceased:'已故的人'}).map(([id,label])=>`<option value="${id}" ${filters.group===id?'selected':''}>${label}</option>`).join('')}</select></label><button class="button secondary" type="submit">查找</button></form>
  <div class="directory-heading"><h2>在生活中相识</h2><span class="small muted" role="status">${loading?'正在翻阅…':`共 ${p.total} 人`}</span></div><div class="people-grid">${p.people.map(person=>`<button class="person-card directory-person ${['dead','deceased'].includes(person.status)?'deceased':''}" data-person="${esc(person.id)}"><canvas class="portrait population-portrait" data-person-id="${esc(person.id)}" aria-label="${esc(person.name)}的像素头像"></canvas><span class="person-main"><span class="person-heading">${esc(person.name)} <small>${person.important?'· 关注中':''}</small></span><span class="person-meta">${esc(person.age)} 岁 · ${esc(person.role&&person.role!=='相识的人'?person.role+' · ':'')}${esc(person.occupation||person.role)}</span><span class="person-description">${esc(person.location)} · ${esc(status(person.status))}</span><span class="person-contact">${person.contact==='direct'?'有过直接交往':'间接听闻'}${person.closeness!=null?` · 亲近 ${person.closeness}`:''}</span></span><span aria-hidden="true">↗</span></button>`).join('')||'<div class="empty-card"><h3>这一页还空着。</h3><p>试试其他范围，或让生活继续向前。</p></div>'}</div>
  <div class="people-pagination"><button class="button secondary" data-people-page="${Math.max(0,p.offset-p.limit)}" ${p.offset===0?'disabled':''}>← 上一页</button><span class="small">${p.total?`${p.offset+1}—${Math.min(p.total,p.offset+p.limit)}`:'0'} / ${p.total}</span><button class="button secondary" data-people-page="${p.offset+p.limit}" ${p.offset+p.limit>=p.total?'disabled':''}>下一页 →</button></div>
  <section class="people-news"><span class="eyebrow">Word reaches you</span><h2>传到耳边的消息</h2>${(p.news||[]).slice().reverse().slice(0,filters.allNews?120:8).map(row=>`<article><span class="small muted">${esc(calendarYear(view.world,row.year))} · ${esc(row.source||'公开消息')}</span><h3>${esc(row.title)}</h3><p>${esc(row.text)}</p></article>`).join('')||'<p class="muted">暂时没有新的消息。</p>'}${(p.news||[]).length>8&&!filters.allNews?'<button class="button secondary more-button" data-action="all-people-news">展开更多消息 ↓</button>':''}</section>`;
}
function renderPerson(person,p,view,loading){
  const cost=action=>Object.entries(action.costs||{}).filter(([,n])=>n>0).map(([key,n])=>`${key==='cash'?'现金':'精力'} ${n}`).join(' · ')||'无资源花费';
  return `<button class="button text-button" data-people-back>← 回到人群</button><article class="person-dossier"><header><canvas class="portrait population-portrait" data-person-id="${esc(person.id)}" aria-label="${esc(person.name)}的像素头像"></canvas><div><span class="eyebrow">${person.contact==='direct'?'相识的人':'听闻的人'}</span><h2>${esc(person.name)}</h2><p>${esc(person.age)} 岁 · ${esc(person.role&&person.role!=='相识的人'?person.role+' · ':'')}${esc(person.occupation||person.role)} · ${esc(status(person.status))}</p></div></header><p class="dossier-description">${esc(person.description)}</p><div class="change-tags">${(person.identities||[]).map(identity=>`<span>${esc(identity)}</span>`).join('')}</div><section><h3>交往中看到的一面</h3><p>${person.known_traits?.length?person.known_traits.map(esc).join('；'):'相处的证据还不够，暂时无法判断。'}</p>${person.motivation?`<p>已知的心愿 · ${esc(person.motivation)}</p>`:''}<p class="small muted">印象来自已知经历，无法概括一个人的全部内心。</p></section>
  ${view.finished?'':`<section><div class="directory-heading"><h3>这一年的来往</h3><span class="small muted">已用 ${p.actions_used} / ${p.actions_limit} 次</span></div><div class="social-actions">${(person.actions||[]).map(action=>`<button class="social-action" data-social="${esc(action.id)}" data-social-person="${esc(person.id)}" ${!action.available||loading?'disabled':''}><strong>${esc(action.label)}</strong><span>${esc(action.description)}</span><small>${esc(cost(action))}</small>${!action.available?`<em>${esc(action.locked_reason)}</em>`:''}</button>`).join('')}</div></section>`}
  ${person.relations?.length?`<section><h3>你知道的关联</h3><div class="relation-links">${person.relations.map(relation=>`<button class="evidence-link" data-person="${esc(relation.id)}">${esc(relation.name)} · ${esc(relation.label)} ↗</button>`).join('')}</div></section>`:''}
  <section><h3>你所知道的经历</h3><p class="small muted">这份笔记只收录你已知的近况和往事；未曾听闻的经历仍留有空白。</p><div class="dossier-timeline">${(person.timeline||[]).slice().reverse().map(row=>`<article><span class="small muted">${esc(calendarYear(view.world,row.year))} · ${esc(row.source||'已知消息')}${row.confidence?` · ${esc(({recorded:'已记录',reported:'转述',observed:'亲历'})[row.confidence]||row.confidence)}`:''}</span><h4>${esc(row.title)}</h4><p>${esc(row.text)}</p></article>`).join('')||'<p class="muted">还没有得知更多经历。</p>'}</div></section></article>`;
}
